// flow-typed signature: bc87f57bf8e545f40d9ceee98af5875b
// flow-typed version: <<STUB>>/go-post-api_vfile:../go-post-api/flow_v0.87.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'go-post-api'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'go-post-api' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'go-post-api/migrations/1_deploy_contracts' {
  declare module.exports: any;
}

declare module 'go-post-api/test/helpers' {
  declare module.exports: any;
}

declare module 'go-post-api/test/test_main' {
  declare module.exports: any;
}

declare module 'go-post-api/truffle' {
  declare module.exports: any;
}

// Filename aliases
declare module 'go-post-api/index' {
  declare module.exports: $Exports<'go-post-api'>;
}
declare module 'go-post-api/index.js' {
  declare module.exports: $Exports<'go-post-api'>;
}
declare module 'go-post-api/migrations/1_deploy_contracts.js' {
  declare module.exports: $Exports<'go-post-api/migrations/1_deploy_contracts'>;
}
declare module 'go-post-api/test/helpers.js' {
  declare module.exports: $Exports<'go-post-api/test/helpers'>;
}
declare module 'go-post-api/test/test_main.js' {
  declare module.exports: $Exports<'go-post-api/test/test_main'>;
}
declare module 'go-post-api/truffle.js' {
  declare module.exports: $Exports<'go-post-api/truffle'>;
}
