// flow-typed signature: d5c9fe6a3f8d5aab2fba7e8af5998050
// flow-typed version: <<STUB>>/informed_v1.10.9/flow_v0.87.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'informed'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'informed' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'informed/dist/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'informed/dist/index.js' {
  declare module.exports: $Exports<'informed/dist/index'>;
}
